version:  '3'
services:
  ServiceCenter:
    image: servicecomb/service-center
    ports:
      - 30100:30100
  php-server:
    build: ./server
    network_mode: "service:mesher-provider"
    depends_on:
      - mesher-provider
  php-client:
    build: ./client
    environment:
      http_proxy: http://127.0.0.1:30101
    network_mode: "service:mesher-consumer"
    depends_on:
      - mesher-consumer
  mesher-provider:
    image: gochassis/mesher:latest
    environment:
      CSE_REGISTRY_ADDR: http://ServiceCenter:30100
      SERVICE_NAME: "hellomesher"
    links:
      - ServiceCenter
  mesher-consumer:
    image: gochassis/mesher:latest
    environment:
      CSE_REGISTRY_ADDR: http://ServiceCenter:30100
      SERVICE_NAME: "mesher-consumer"
    links:
      - ServiceCenter


